services:
    app_portal.email_blackList_validator:
        class: App\PortalBundle\Validator\Constraints\EmailBlackListValidator
        calls:
            - [ setBlackList, [ "%mail_blacklist%" ] ]
        tags:
            - { name: validator.constraint_validator, alias: email_black_list }