imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: form.yml }
    - { resource: listener.xml }
    - { resource: mail_blacklist.yml }
    - { resource: manager.yml }
    - { resource: repository.yml }
    - { resource: services.xml }
    - { resource: services.yml }
    - { resource: twig.xml }
    - { resource: validator.yml }
    - { resource: user/authentication.yml }
    - { resource: user/form.xml }
    - { resource: user/listener.xml }
    - { resource: user/manager.xml }
    - { resource: user/repository.xml }
    - { resource: user/services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    #redirection_url_after_access_denied_exception: homepage

framework:
    #esi: ~ # Pour utiliser les tags ESI dans les templates Twig
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        website: mywebsite

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                DAY: DoctrineExtensions\Query\Mysql\Day
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR:  DoctrineExtensions\Query\Mysql\Year
                DATE: DoctrineExtensions\Query\Mysql\Date
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true

liip_imagine:
    filter_sets:
        movie_thumbnail:
            quality: 100
            filters:
                relative_resize: { widen: 200 }

services:
    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
    twig.extension.date:
            class: Twig_Extensions_Extension_Date
            tags:
                - { name: twig.extension }
    twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }
    twig.extension.array:
            class: Twig_Extensions_Extension_Array
            tags:
                - { name: twig.extension }
    twig.extension.i18n:
            class: Twig_Extensions_Extension_I18n
            tags:
                - { name: twig.extension }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\BackUser
    from_email:
        address:        '%email_from%'
        sender_name:    Admin

app:
    max_hashtag_limit: 3
    max_movies_per_page: 5
    max_actors_per_page: 5