imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:           rotating_file
            max_files:      3
            path:           "%kernel.logs_dir%/%kernel.environment%.all.log"
            level:          info
            channels:       [!doctrine, !security]
        doctrine:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            channels:       doctrine
        authentication:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       security #mywebsite_user
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.error.log"
            level:          info
        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
        grouped_critical:
            type:           group
            members:        [streamed_critical, buffered_critical]
        streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level:          info
        buffered_critical:
            type:           buffer
            handler:        swift_critical
        swift_critical:
            type:           swift_mailer
            from_email:     contact@mywebsite.com
            to_email:       jpsymfony@free.fr
            subject:        Une erreur critique est survenue !
            level:          info
        console:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE
            formatter: mywebsite_formatter


app:
   max_hashtag_limit: 8
   payment_organisms:
       default: Be2bill
       Be2bill:
           identifier: MYWEBSITE
           password: 987654321
           url: https://secure-magenta1.be2bill.com/front/form/process.php
       Paypal:
           identifier: me@mywebsite.com
           password: ~
           url: http://www.paypal.com/cgi-bin/webscr
