services:
    kernel.listener.console_exception:
            class: App\CoreBundle\EventListener\ConsoleExceptionListener
            arguments:
                logger: '@logger'
            tags:
                - { name: kernel.event_listener, event: console.exception }

    kernel.listener.console_terminate_dispatch:
            class: App\CoreBundle\EventListener\ErrorLoggerListener
            arguments:
                logger: '@logger'
            tags:
                - { name: kernel.event_listener, event: console.terminate }

    mywebsite_formatter:
            class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
            arguments:
                - "[%%datetime%%] %%start_tag%%%%message%%%%end_tag%% (%%level_name%%) %%context%% %%extra%%\n"