services:
    app.email_blackList_validator:
        class: AppBundle\Validator\Constraints\EmailBlackListValidator
        calls:
            - [ setBlackList, ['%mail_blacklist%'] ]
        tags:
            - { name: validator.constraint_validator, alias: email_black_list }