## Configuration Apache
web:
   restart: always
   container_name: apache
   build: apache
   ports:
      - "80:80"
   volumes:
      - /var/www/mes_projets_symfony/alterway-demo:/var/www/mes_projets_symfony/alterway-demo
      - /var/www/mes_projets_symfony/alterway-demo/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
      - /var/www/mes_projets_symfony/alterway-demo/docker/config:/etc/apache2/sites-enabled
   environment:
      - ALLOW_OVERRIDE=true
   links:
      - db:db
      - blackfire:blackfire
   volumes_from:
      - data

data:
   container_name: data
   image: busybox
   volumes:
      - /var/www/mes_projets_symfony/alterway-demo/app/cache
      - /var/www/mes_projets_symfony/alterway-demo/app/logs

blackfire:
   restart: always
   container_name: blackfire
   image: blackfire/blackfire
   environment:
      - BLACKFIRE_SERVER_ID=e290f312-2df3-494b-9c75-74f40d49ab95
      - BLACKFIRE_SERVER_TOKEN=afca3603f53ce551ea48b51d4aafd3951533b98537df34c54965db741a5869de

db:
   restart: always
   container_name: db
   image: mysql
   volumes:
      - /var/lib/boot2docker/mysql:/var/lib/mysql
   environment:
      - MYSQL_ROOT_PASSWORD=root

gatling:
    container_name: gatling
    image: webdizz/gatling
    volumes:
      - /var/www/mes_projets_symfony/alterway-demo/gatling/properties:/opt/gatling/properties
      - /var/www/mes_projets_symfony/alterway-demo/gatling/scripts:/scripts
      - /var/www/mes_projets_symfony/alterway-demo/gatling/scala:/opt/gatling/user-files/simulations
      - /var/www/mes_projets_symfony/alterway-demo/gatling/resources/data:/opt/gatling/user-files/data
      - /var/www/mes_projets_symfony/alterway-demo/gatling/resources/bodies:/opt/gatling/user-files/bodies
      - /var/www/mes_projets_symfony/alterway-demo/gatling/resources/conf/gatling.conf:/opt/gatling/conf/gatling.conf
      - /var/www/mes_projets_symfony/alterway-demo/gatling/resources/conf/application.conf:/opt/gatling/conf/application.conf
      - /var/www/mes_projets_symfony/alterway-demo/gatling/results:/opt/gatling/results